#!/bin/bash
# autobuild functions, shebang for syntax.

# misc functions
returns(){ return $1; }
commaprint(){
	local FIRST=true
	for i; do
		! $FIRST && echo -n ' , ' || FIRST=false
		echo -n $i;
	done
}
varcheck(){	# is it empty?
	declare -gn vchk
	local ret=0
	for vchk; do [ -z "$vchk" ] && ret=1 && break; done
	declare -g +n vchk # Say its name
	return $ret
}
dumparg(){ for i; do printf '%q ' "$i"; done; }
_ab_rsor(){ for i; do [[ -e "$i" ]] && . "$i"; done; }
_ab_plug(){ for i; do _ab_rsor $ABLE/plugin/{,$ARCH_}$i_*.sh; done; }

# build functions
build_self(){
	. $SRCDIR/autobuild/build
}
build_autotools(){
	[ -z "$ABSHADOW" ] && mkdir -p build && cd build
	$SRCDIR/${configure} --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libexecdir=/usr/lib/$PKGNAME $AUTOTOOLS_AFTER &&
	make $ABMK $MAKE_AFTER &&
	make DESTDIR=$PKGDIR $MAKE_AFTER install
}
build_cmake(){
	[ -z "$ABSHADOW" ] && mkdir -p build && cd build
	cmake "$SRCDIR" -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release $CMAKE_AFTER &&
	make $ABMK $MAKE_AFTER &&
	make DESTDIR=$PKGDIR $MAKE_AFTER install
}
build_perl(){
	perl Makefile.PL && make && make DESTDIR=$PKGDIR install
}
build_python(){
	$PYTHON setup.py bdist &&
	cd dist &&
	tar xvf *.tar.* &&
	rm *.tar.* &&
	cd .. &&
	mv dist "$PKGDIR"
}
build_qtproject(){
	# qt5 packages: please use PATH="/usr/lib/qt5/bin:$PATH" in defines
	qmake && make $ABMK
}

# build related
detect_type(){
	if [ -e autobuild/build ]
	then
		echo "self"
	elif [ -e configure ]
	then
		echo "autotools"
	elif [ -e CMakeLists.txt ]
	then
		echo "cmake"
	elif [ -e setup.py ]
	then
		echo "python"
	elif [ -e Makefile.PL ]
	then
		echo "perl"
	elif [ "*.pro" != '*.pro' ]
	then
		echo "qtproject"
	else
		echo "unsupported"
	fi
}

# a more precise one
# addalt link name path prio
addalt(){
	echo "update-alternatives --install $(dumparg "$@")" >> abdist/postinst
	echo "update-alternatives --remove $(dumparg "$2" "$3")" >> abdist/prerm
}

# alternative path link prio [path2 link2 prio2 ..]
alternative(){ while [ ! -z "$1" ]; do addalt "$1" "$(basename "$1")" "$2" "$3"; shift 3; done; }

