#! /bin/bash
eval unset $_ab_pm
getver(){
    dpkg-query -f '${Version}' -W $1 2>/dev/null
}

# dpkg field helper.
_ab_pm_func+='field pkgver'
field(){ echo -ne "$1: "; shift; depcom "$@"; echo; }
pkgver(){ ((PKGEPOCH)) && echo -n $PKGEPOCH:; echo -n "$PKGVER"; ((PKGREL)) && echo "-$PKGREL"; }

mkctrl(){
	echo "Package: $PKGNAME"
	echo "Version: $(pkgver)"
	echo "Architecture: $ARCH"
	[ "$PKGSEC" ] && echo "Section: $PKGSEC"
	echo "Maintainer: $MTER"
	echo "Installed-Size: $(du -s $PKGDIR | cut -f 1)"
	echo "Description: $PKGDES"
	field Depends $PKGDEP
	VER_NONE=1 # We don't autofill versions in optional fields
	[ "$PKGRECOM" ] && field Recommends $PKGRECOM
	[ "$PKGREP" ] && field Replaces $PKGREP
	[ "$PKGCONFL" ] && field Conflicts $PKGCONFL
	[ "$PKGPROV" ] && field Provides $PKGPROV
	[ "$PKGBREAK" ] && field Breaks $PKGBREAK
}

pack(){
	mkdir -p $PKGDIR/DEBIAN
	cp -rl $SRCDIR/abscripts/* $PKGDIR/DEBIAN
	cp -l $SRCDIR/autobuild/conffile $PKGDIR/DEBIAN 2>/dev/null
	mkctrl > $PKGDIR/DEBIAN/control &&
	dpkg-deb -Zxz -z9 -Sextreme -b $PKGDIR ${PKGNAME}.deb &&
	dpkg -i ${PKGNAME}.deb
	mv $PKGDIR/DEBIAN $SRCDIR/ab-dpkg
}

getdep(){
	if ! dpkg -l $BUILDDEP $PKGDEP; then
        	apt-get update 
        	apt-get install $BUILDDEP $PKGDEP --yes
	fi
}
