#! /bin/bash
getver(){
        COLUMNS=1 dpkg -l $1 | grep ^ii | cut -c 20- | cut -d " " -f 1
}

cprint(){ echo -ne "$1: "; shift; commaprint "$@"; echo; }

# TODO: genver(name[OPversion | _]) -> buf+="name [dpkg ver str]" + (first?'':'|')
# TODO: i.split('|').foreach(genver) // dpkg-specific
gendep(){
	echo -ne 'Depends: '
	local FIRST=true
	for i in $PKGDEP
	do
		! $FIRST && echo -n ', ' || FIRST=false
		echo -n "$i"
		[ "$(cut -d\| -f 1 <<< "$i" )" == "$i" ] &&
			echo -n "(>= `getver $i`)"
	done
	echo
}

mkctrl(){
	echo "Package: $PKGNAME"
	echo "Version: $PKGVER"
	echo "Architecture: $ARCH"
	[ "$PKGSEC" ] && echo "Section: $PKGSEC"
	echo "Maintainer: $MTER"
	echo "Installed-Size: $(du -s $PKGDIR | cut -f 1)"
	echo "Description: $PKGDES"
	gendep
	# optional fields
	[ "$PKGRECOM" ] && cprint Recommends $PKGRECOM
	[ "$PKGREP" ] && cprint Replaces $PKGREP
	[ "$PKGCONFL" ] && cprint Conflicts $PKGCONFL
	[ "$PKGPROV" ] && cprint Provides $PKGPROV
	[ "$PKGBREAK" ] && cprint Breaks $PKGBREAK
}

pack(){
	cp -rl $SRCDIR/abscripts $PKGDIR/DEBIAN
	mkctrl > $PKGDIR/DEBIAN/control &&
	dpkg-deb -Zxz -z9 -Sextreme -b $PKGDIR ${PKGNAME}.deb &&
	dpkg -i ${PKGNAME}.deb
}

getdep(){
	if ! dpkg -l $BUILDDEP $PKGDEP; then
        	apt-get update 
        	apt-get install $BUILDDEP $PKGDEP --yes
	fi
}
