#! /bin/bash
export ABPF=/usr
export ABLE=$ABPF/lib/autobuild
export ARCH=amd64
export MTER="Jeff Bai <jeffbaichina@gmail.com>"

export DPKGDEBFLAGS="-Zxz -z9"

# programs
# Standard announcements
echo "Developers:"
echo "* This is the upstream of :Next, DO NOT ever try to use binaries/packages from other distros!"
echo "* Don't forget to upload the autobuild archive with the package!"
echo "* Never try to do something unnecessary, as they won't be accepted!"
echo " "
echo "So seriously, quality control:"
echo "1. The packages should be built from source, when they are available, packages should be uploaded along with the autobuild archive;"
echo "2. It's not allowed to re-upload the package(s) without a confirmed bug report;"
echo "3. Try your best to obey the quality control."
read -sn 1 -p "Press any key to continue..."

if [ "x$PYTHON" = "x" ]
then
	export PYTHON=python
fi

if [ -e $ABLE/functions ]
then
	. $ABLE/functions
else
	# default defines
	dpkg_getver(){
#		dpkg -l $1 | grep ^ii | cut -c 5- | cut -d " " -f 1
		COLUMNS=1 dpkg -l $1 | grep ^ii | cut -c 20- | cut -d " " -f 1
	}
	detect_type(){
		if [ -e autobuild/build ]
                then
                        echo "self"
		elif [ -e configure ]
		then
			echo "autotools"
		elif [ -e CMakeLists.txt ]
		then
			echo "cmake"
		elif [ -e autobuild/build ]
		then
			echo "self"
                elif [ -e SConstruct ]
                then
                        echo "scons"
                elif [ -e setup.py ]
                then
                        echo "python"
		else
			echo "unsupported"
		fi
	}
	autobuild_autotools(){
		SRCDIR=`pwd`
		if [ "x$ABSHADOW" = "x" ] 
		then
			mkdir -p build &&
			cd build
		else 
			true
		fi && 
		$SRCDIR/configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libexecdir=/usr/lib/$PKGNAME $AUTOTOOLS_AFTER && 
		make $ABMK $MAKE_AFTER && 
		make DESTDIR=$SRCDIR/abdist $MAKE_AFTER install && 
		if [ "x$ABSHADOW" = "x" ] 
		then 
			cd ..
		else
			true
		fi
	}
	autobuild_cmake(){
                mkdir -p build && 
		cd build && 
		cmake .. -DCMAKE_INSTALL_PREFIX=/usr $CMAKE_AFTER && 
		make $ABMK $MAKE_AFTER && 
		make DESTDIR=`pwd`/../abdist $MAKE_AFTER install && 
		cd ..
        }
	autobuild_self(){
		bash `pwd`/autobuild/build
	}
	autobuild_scons(){
		scons --prefix=/usr --install-sandbox=`pwd`/abdist install
	}
	autobuild_python(){
		$PYTHON setup.py bdist &&
		cd dist &&
		tar xvf *.tar.* &&
		rm *.tar.* &&
		cd .. &&
		mv dist abdist
	}
	gendep(){
		FIRST=1
		for i in $PKGDEP
		do
			[ "$FIRST" != "1" ] && printf ", "
			[ "$FIRST" = "1" ] && FIRST=0
			printf "$i (>= `dpkg_getver $i`)"
		done
	}
	gen_control(){
		mkdir -p abdist/DEBIAN && 
		echo "Package: $PKGNAME" > abdist/DEBIAN/control && 
		echo "Version: $PKGVER" >> abdist/DEBIAN/control && 
		echo "Architecture: $ARCH" >> abdist/DEBIAN/control && 
		( ( [ "x$PKGSEC" != "x" ] && echo "Section: $PKGSEC" >> abdist/DEBIAN/control ) || true ) && 
		echo "Maintainer: $MTER" >> abdist/DEBIAN/control &&
		echo "Installed-Size: `du -s abdist | cut -f 1`" >> abdist/DEBIAN/control && 
		echo "Description: $PKGDES" >> abdist/DEBIAN/control && 
		if [ "x$PKGDEP" != "x" ]
		then 
			echo "Depends: `gendep`" >> abdist/DEBIAN/control
		else
			true
		fi
	}
fi

if [ ! -d autobuild ]
then
	echo No autobuild directory ^o^
	exit 1
fi

if [ -e autobuild/defines ]
then
	. autobuild/defines
else
	echo "No autobuild/defines :-("
	exit 1
fi

if [ "x$ABTYPE" = "x" ]
then
	export ABTYPE="`detect_type`"
fi

if [ -e autobuild/patch ]
then
	if [ ! -e .patch ]
	then
		. autobuild/patch
		touch .patch
	fi
fi

if autobuild_$ABTYPE
then
	:
else
	echo "Build failed..."
	exit 1
fi

if [ ! -d abdist ]
then
	echo No abdist ^o^
	exit 1
fi

if [ -d autobuild/override ]
then
	cp -r --preserve=all autobuild/override/* abdist
fi

if [ -e autobuild/beyond ]
then
	. autobuild/beyond
fi

# Experimental linking support
if [ -e autobuild/links ]
then
	. autobuild/links
fi

# Begin plugins

# remove dir

rm -f abdist/usr/share/info/dir
rm -f abdist/usr/info/dir

# End plugins

if [ ! -e autobuild/subpkgs ]
then

gen_control

touch abdist/DEBIAN/postinst
chmod 755 abdist/DEBIAN/postinst

touch abdist/DEBIAN/prerm
chmod 755 abdist/DEBIAN/prerm


alternative(){
	while [ "x$1" != "x" ]
	do
		echo "update-alternatives --install $1 `basename $1` $2 $3 " >> abdist/DEBIAN/postinst
		echo "update-alternatives --remove `basename $1` $2" >> abdist/DEBIAN/prerm
		shift
		shift
		shift
	done
}

if [ -e autobuild/alternatives ]
then
	. autobuild/alternatives
fi

dpkg-deb $DPKGDEBFLAGS -b abdist && dpkg -i abdist.deb

fi
