#! /bin/bash
. autobuild/defines
if [ "x$ABSHADOW" = "x" ] 
then
	mkdir -p build &&
	cd build
else 
	true
fi && 
$SRCDIR/${configure} --prefix=/usr --sysconfdir=/etc --localstatedir=/var --libexecdir=/usr/lib/$PKGNAME $AUTOTOOLS_AFTER && 
make $ABMK $MAKE_AFTER && 
make DESTDIR=$PKGDIR $MAKE_AFTER install && 
if [ "x$ABSHADOW" = "x" ] 
then 
	cd ..
else
	true
fi
