#!/bin/bash
# This is an experimental QA Check module for autobuild.
# Feel free to add more to it.
#
# Just yet another Developer.

# Check prefix now.
if [ -d $PKGDIR/usr/local ]; then
  echo -e "\e[31m/usr/local exists in your package tree!\e[0m"
  echo "This breaks the QA policy of AOSC OS3, please check back on your AUTOTOOLS_AFTER, CMAKE_AFTER or autobuild/build scriptlet."
  read -n 1 -p "Press any key to continue or C-c to quit..."
else
  echo -e "\e[32mDirectory tree looks good so far, proceeding...\e[0m"
fi

# Check sections
# 前方高能刷屏，无关人员请迅速撤离
qa_sec(){
#STARTSEC
  for qa_s in admin cli-mono comm database debian-installer debug \
  devel doc editors eletronics embedded fonts games gnome gnu-r gnustep \
  graphics hamradio haskell httpd interpreters java kde \
  kernel libdevel libs lisp localization mail math misc net news \
  ocaml oldlibs otherosfs perl php python ruby science shells \
  sound tex text utils vcs video virtual web x11 xfce zope
#ENDSEC
    do [ "$PKGSEC" == $qa_s ] && return 0; done
  return 1
}


if qa_sec
then echo -e "\e[32mSection looks great, proceeding...\e[0m" 
else echo -e "\e[31mSection not in the stardard sections list. See https://github.com/AOSC-Dev/autobuild3/blob/master/sets/section or $ABLE/qa.\e[0m"
  read -n 1 -p "Press any key to continue or C-c to quit..."
  echo
fi

# Here above is all I can think of so far, feel free to add more.
#
# Well I have a TODO list here, not implemented yet:
#
# 1. Check for invalid symlinks
# 2. Check for free files in / or /usr/
# 3. ShLibDeps... Good ol' toolset.
