#! /bin/bash
export ABPF=/usr
export SRCDIR="$PWD" PKGDIR="$PWD/abdist"
export PYTHON=${PYTHON=/usr/bin/python}
ABLE=$ABPF/lib/autobuild
ARCH=amd64
MTER="$(cat /etc/maintainer || echo 'Unknown UNKNOWN <unknown@unknown.moe>')"
ABPM=dpkg
die(){ echo -ne '\e[31m'; echo "$1">&2; echo -ne '\e[0m'; exit ${2-1}; }

# Where are we?
if [ ! -d $ABLE ]
then
	echo "Autobuild installation not found. Using self…"
	export ABPF=$(dirname $0)
	ABLE=$ABPF/libexec
fi
export ABLE

# integrity check
. $ABLE/base || die "autobuild base function import failed"
. $ABLE/$ABPM || die "$ABPM packing function import failed"

[ -d autobuild ] || die "autobuild directory doesn't exist man... relax... ^O^"
# what's the point for the emotion character...

if [ -e autobuild/defines ]
then
	. autobuild/defines
	[ "$PKGDES" ] || PKGDES="$PKGDESC" # Be PKGBUILD-user-friendly
	varcheck PKG{NAME,VER,DES} || die "Package info $vchk missing."
else
	die "No autobuild/defines :-("
fi

if [ "$configure" != "configure" ]; then ABSHADOW=no; ABTYPE=autotools; fi
[[ "$PKGNAME" =~ +32$ ]] && BUILDDEP+=' 32subsystem'

# get necessary dependencies defined in define before build
# BUILDDEP+PKGDEP=***REAL*** Needed stuff.
if ! dpkg -l $BUILDDEP $PKGDEP
then
        apt-get update 
        apt-get install $BUILDDEP $PKGDEP --yes
fi

if [ -e autobuild/patch ] && [ ! -e .patch ]
then
  . autobuild/patch
  cd $SRCDIR
  touch .patch
fi

build_${ABTYPE=$(detect_type)} || die "Build failed..."

if [ $LICENSE == yes ] && [ -e LICENSE ] || mv COPYING LICENSE
then
	mkdir -p abdist/usr/share/licenses/${PKGNAME}
	cp COPYING abdist/usr/share/licenses/${PKGNAME}/LICENSE
fi

# QA call.
. $ABLE/qa

# Backported elf strip.
. $ABLE/elf

[  -d abdist ] || die 'No abdist ^o^'

# Backport the overrides, which can be later overwritten easily.
[ -d autobuild/overrides ] && cp -la autobuild/overrides/* abdist
# abscript TODO.

if [ -d autobuild/override ]
then
	cp -a autobuild/override/* abdist
fi

if [ -e autobuild/beyond ]
then
	. autobuild/beyond
fi

cd $SRCDIR

# Begin plugins

# Remove dir

rm -f abdist/usr/share/info/dir
rm -f abdist/usr/info/dir

# remove Perl info

rm -f /usr/lib/perl5/*/perllocal.pod
rm -f /usr/lib/perl5/*/*/perllocal.pod

# End plugins

[ -e autobuild/subpkgs ] && exit

if [ -e autobuild/alternatives ]
then
	. autobuild/alternatives
fi

chmod a-s abdist/DEBIAN

pack && ${NOARCHIVE-true} && tar -cvJf ${PKGNAME}_${PKGVER//:/_}.tar.xz ./autobuild
