#! /bin/bash
export ABPF=/usr
export ABLE=$ABPF/lib/autobuild
export ARCH=amd64
export MTER="`cat /etc/maintainer`"
export ABTGTPM=dpkg
export DEBFILE=$echo("$PKGNAME"_"$PKGVER".deb)
export DPKGDEBFLAGS="-Zxz -z9"

# programs

if [ "x$PYTHON" = "x" ]
then
	export PYTHON=/usr/bin/python
fi

if [ -e $ABLE/functions ]
then
	. $ABLE/functions
else
	echo "Installation not full!"
	exit 1
fi

if [ ! -d autobuild ]
then
	echo No autobuild directory ^o^
	# what's the point for the emotion character...
	exit 1
fi

if [ -e autobuild/defines ]
then
	. autobuild/defines
else
	echo "No autobuild/defines :-("
	exit 1
fi

# get necessary dependencies defined in define before build
# BUILDDEP+PKGDEP=***REAL*** Needed stuff.
if dpkg -l $BUILDDEP $PKGDEP
then
        true
else
        apt-get update 
        apt-get install $BUILDDEP $PKGDEP
fi

if [ "x$ABTYPE" = "x" ]
then
	export ABTYPE="`detect_type`"
fi

if [ -e autobuild/patch ]
then
	if [ ! -e .patch ]
	then
		. autobuild/patch
		touch .patch
	fi
fi

if autobuild_$ABTYPE
then
	:
else
	echo "Build failed..."
	exit 1
fi

if [ ! -d abdist ]
then
	echo No abdist ^o^
	exit 1
fi

if [ -d autobuild/override ]
then
	cp -r --preserve=all autobuild/override/* abdist
fi

if [ -e autobuild/beyond ]
then
	. autobuild/beyond
fi

# Begin plugins

# remove dir

rm -f abdist/usr/share/info/dir
rm -f abdist/usr/info/dir

# remove perl info

rm -f /usr/lib/perl5/*/perllocal.pod
rm -f /usr/lib/perl5/*/*/perllocal.pod

# End plugins

if [ ! -e autobuild/subpkgs ]
then

PKGNAME=$PKGNAME PKGVER=$PKGVER PKGDEP=$PKGDEP PKGSEC=$PKGSEC PKGDES=$PKGDES PKGCONFL=$PKGCONFL PKGRECOM=$PKGRECOM PKGREP=$PKGREP PKGPROV=$PKGPROV PKGBREAK=$PKGBREAK gen_control

touch abdist/DEBIAN/postinst
chmod 755 abdist/DEBIAN/postinst

touch abdist/DEBIAN/prerm
chmod 755 abdist/DEBIAN/prerm


alternative(){
	while [ "x$1" != "x" ]
	do
		echo "update-alternatives --install $1 `basename $1` $2 $3 " >> abdist/DEBIAN/postinst
		echo "update-alternatives --remove `basename $1` $2" >> abdist/DEBIAN/prerm
		shift
		shift
		shift
	done
}

if [ -e autobuild/alternatives ]
then
	. autobuild/alternatives
fi

chmod a-s abdist/DEBIAN

dpkg-deb $DPKGDEBFLAGS -b abdist $DEBFILE && dpkg -i $DEBFILE
fi
